### PR TITLE
new folder structure

### PR DESCRIPTION
**Pull request by cipher-shad0w**
image

### CODE REVIEW

**Comment by cipher-shad0w** [comment]
It doesn't work yet. Pls not confirm

**Comment by cipher-shad0w** [comment]
I only optimize the structure and the imports, nothing else.

**Review by mirixy — APPROVED** [review]
Seems to be okay, I have no objections.

**Comment by arvedb** [comment]
The folder structure looks good!

**Review by arvedb — APPROVED** [review]
Folder structure looks grerat. Streamlit app is starting properly, transcription still working. Pull request approved.

**Pull request merged**
